name: Production Deployment

on:
  workflow_dispatch:

jobs:
  prod-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull image on production server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PRODUCTIESERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/calculator:test

      - name: Start container on production server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PRODUCTIESERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop calculator || true
            docker rm calculator || true
            docker run -d --name calculator -p 80:3000 ${{ secrets.DOCKERHUB_USERNAME }}/calculator:test

      - name: Test production
        run: |
          sleep 10
          curl -f http://${{ secrets.PRODUCTIESERVER_IP }}
